### ISSUE TITLE
How to replace h2 with mysql/postgres

### ISSUE THREAD

**Issue by alexksg** [marcosbarbero/spring-boot2-oauth2-jwt#3]
Could you provide a basic example of replacing h2 provider to a relational db. Thanks

**Comment by marcosbarbero** [comment]
Hi @coilnovasince1985 it's pretty simple. Just follow the steps:

1. Convert the [schema.sql](https://github.com/marcosbarbero/spring-boot2-oauth2-jwt/blob/master/oauth2-jwt-server/src/main/resources/schema.sql) to your database.
1. Configure your `DataSource` in your `application.yml`, you can find the available properties at [Spring's official documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html)

**Comment by alexksg** [comment]
@marcosbarbero Alright, basically i've setup a postgres connection and postgres schema, authentication works fine for clientId, but then my oauth tables are empty upon successful login. Do I need to manually fill up tables with the access, refresh token information or i missed something out ?

**Comment by marcosbarbero** [comment]
I get you now! That's the thing with JWT it doesn't have token storage, and that's why you can't find the tokens on the tables.

**Comment by alexksg** [comment]
@marcosbarbero I've previously read an article where they trying to create a jwt storage, so is that what it means ? If I implement my own jwtTokenStorage I can take advantage of those tables ?

**Comment by marcosbarbero** [comment]
if you implement it then you can store data in there, you can use the `JdbcTokenStore` for inspiration. But I personally wouldn't do that. By doing that it kinda loses its purpose.

**Comment by coilnovasince1985** [comment]
@marcosbarbero will look into it! Anyway thank you for this repo, really nice job. I have the last question basically and its regarding the frontend like angular. How does the flow goes if I need to use frontend app to communicate with the backend api. As I understand currently I need to make a post request like the one in example with a clientId and secret to the auth server first then store the token on my frontend and pass it with an every request to a desired resource server. And then track the expiry time and request the new token upon expiry. Is it how the flow goes with the current oauth approach ?

And does the refresh token currently works with this repository? 🙏
