### ISSUE TITLE
oauth/authorize Authorization Code

### ISSUE THREAD

**Issue by alexksg** [marcosbarbero/spring-boot2-oauth2-jwt#4]
Could you please show an example on how can I get an authorization code for obtaining an access code?
Do we need to edit some configuration or its already working out of the box ?

I've tried the following URL as a sample:
http://localhost:9000/oauth/authorize?client_id=client_1&response_type=code&scope=read
but receiving
```
{
  "timestamp": "2019-12-27T05:39:18.810+0000",
  "status": 403,
  "error": "Forbidden",
  "message": "Access Denied",
  "path": "/oauth/authorize"
}
```

**Comment by marcosbarbero** [comment]
Hi @coilnovasince1985 authorization code grant is not configured in the `insert` statement at the [data.sql](https://github.com/marcosbarbero/spring-boot2-oauth2-jwt/blob/master/oauth2-jwt-server/src/main/resources/data.sql#L3) file.

If you configure it there then it should work.

**Comment by alexksg** [comment]
@marcosbarbero yes I've updated the records in my db to include all auth types and then I receive access denied :(

btw: is the link im trying to hit correct ?

**Comment by marcosbarbero** [comment]
is it on github? I can take a look for you

**Comment by alexksg** [comment]
@marcosbarbero actually its purely your source code running with postgres instead of mysql, nothing else is changed. All other types are working fine except authorization_code

Can you try my link under your side and comment if its actually working ?

**Comment by marcosbarbero** [comment]
I see, there should be a few more stuff to do to make it work.
I'll try to adjust my example by tomorrow and tell you.

**Comment by alexksg** [comment]
@marcosbarbero alright, thank you very much as it would be really useful for me and a complete tutorial too

**Comment by marcosbarbero** [comment]
Hi @coilnovasince1985 took me a while but here you go.
Take a look at this commit https://github.com/marcosbarbero/spring-boot2-oauth2-jwt/commit/176c1c0537aa8f8575da7e37216dc0970ed17749.

I didn't set up the landing page on the `resource-app` but you can get the idea.

To test it out you can open the following link in the browser:
http://localhost:9000/oauth/authorize?grant_type=authorization_code&response_type=code&client_id=clientId&state=1234

**Comment by alexksg** [comment]
@marcosbarbero oh thanks man!Will try it out now, Happy new year =))

**Comment by marcosbarbero** [comment]
A happy new year for yourself as well!
