### ISSUE TITLE
Refresh token flow

### ISSUE THREAD

**Issue by giribhagwan** [marcosbarbero/spring-boot2-oauth2-jwt#5]
Hi Marcos,
It too pretty good example you have put. it really helpful to developers.
i just want to know from you, about refresh token.
**how we can refresh access token using refresh token ?**

i will be fantastic if you provide me the any way-out.

**Comment by alexksg** [comment]
@giribhagwan 
You can refresh token using following API:
localhost:9000/oauth/token

**Params:**
Content-Type: application/x-www-form-urlencoded

key: **refresh_token** - value: your refresh token
key: **grant_type** - value: refresh_token

**Comment by giribhagwan** [comment]
Thank you is working...
